CREATE TABLE car (id SERIAL PRIMARY KEY, brand TEXT NOT NULL, model TEXT NOT NULL, price INT CHECK (price > 0));
CREATE TABLE human (id SERIAL PRIMARY KEY, name TEXT NOT NULL UNIQUE, age INT CHECK (age > 0), license BOOLEAN DEFAULT FALSE, car_id INTEGER REFERENCES car(id));
